### ISSUE TITLE
When I run the program, I get an error.

### ISSUE THREAD

**Issue by it19862** [janpavlis/TotalWfx.NET#1]
Visual Studio 2015 x64

Серьезность	Код	Описание	Проект	Ранг проекта	Файл	Строка	Столбец	Категория	Источник	Состояние подавления	Средство
Ошибка	CS1026	Требуется ")"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\WinApi\WIN32_FIND_DATA.cs	37	44	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1002	Требуется ";".	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\WinApi\WIN32_FIND_DATA.cs	37	52	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\WinApi\WIN32_FIND_DATA.cs	37	52	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1026	Требуется ")"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\ManagedWrapper\WfxManagedWrapper.cs	42	56	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1002	Требуется ";".	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\ManagedWrapper\WfxManagedWrapper.cs	42	77	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\ManagedWrapper\WfxManagedWrapper.cs	42	77	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\WinApi\WIN32_FIND_DATA.cs	43	14	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1026	Требуется ")"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	79	54	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1002	Требуется ";".	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	79	68	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	79	68	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	82	18	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1026	Требуется ")"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	83	54	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1002	Требуется ";".	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	83	55	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	83	55	Compiler	IntelliSense	Активно	Компилятор
Ошибка	CS1513	Требуется "}"	TotalWfx.NET	1	E:\instr\github\clon\TotalWfx.NET\TotalWfx.NET\VirtualFilesystem\VirtualFilesystemUtils.cs	86	18	Compiler	IntelliSense	Активно	Компилятор

**Comment by janpavlis** [comment]
Program is not finished, so it is not expected to work for now. I started this project some time ago, but didn't have time to finish it. Hoping I will have time later this year.
